version: '3'

services:
  gateway:
    build:
      context: ../.. # Di solito i Dockerfile si mettono nella root, avendone più di uno però (dev e prod) per ordine facciamo un'altra cartella. Dobbiamo dunque cambiare il contesto salendo di due cartelle.
      dockerfile: infrastructure/dev/dockerfiles/std.node.Dockerfile
      args:
        SERVICE_PATH: ./chef-desires-gateway
    volumes:
      - ../../chef-desires-gateway:/usr/src/server
    ports:
      - '3000:3000'
    networks:
      - recipes

  recipes:
    build:
      dockerfile: infrastructure/dev/dockerfiles/std.node.Dockerfile
      context: ../..
      args:
        SERVICE_PATH: ./chef-desires-recipes
    volumes:
      - ../../chef-desires-recipes:/usr/src/server
    networks:
      - recipes
      - sql_server
    ports:
      - '3001:3000'
  
  sql_server:
    image: mcr.microsoft.com/mssql/server
    container_name: sql_server_container
    restart: always
    env_file:
      - dev.env
    ports:
      - "5533:1433"
    networks:
      - sql_server
    volumes:
      - "./data:/var/opt/mssql/data"

networks:
  recipes:
  sql_server: